### ISSUE TITLE
Не отображается автотюнинг

### ISSUE THREAD

**Issue by No4NaMe** [StrixG/driftparadise-legacy#5]
Не отображаются наклейки и цвет машины скажите почему?

**Comment by No4NaMe** [comment]
вернее не изменяется цвет компонентов, в чем может быть причина?

**Comment by JluHeuKa** [comment]
Именно самих помпонентов нет и как их ставить на машину я хз

**Comment by JluHeuKa** [comment]
А цвет помпонентов не меняется скорее всего то что там текстура не такая лежит, она должна быть такая же как и у кузова
